### ISSUE TITLE
Release under an actual license

### ISSUE THREAD

**Issue by EugeneKay** [zedshaw/fuqit#1]
Requesting that this project be released under an actual, named license. Code with "no license" cannot really be used by any commercial entity, as there are no rights granted by this lack-of-license. Suggesting a switch to the WTFPL, which permits anybody to DO WHAT THE FUCK THEY WANT TO, which is substantially more than "nothing", and meets the same goal of "fuck it" as the existing LICENSE file.

**Comment by zedshaw** [comment]
Uh I hate to break it to you my friend but the _default_ no-license mode for any works created is that they are copyright.   A license is permission from _me_ for you to use my software counter to normal copyright and fair use.  I'm being nice by just saying that while I decide.  If you think that not including a license means something is public domain then you are high.

**Comment by EugeneKay** [comment]
I don't know what you're reading, but this is the exact opposite complaint of Public Domain: no rights being granted at all. Legally you're only saying "Here's some shit that I wrote"; nowhere is it said what we're allowed to do with it.

**Comment by artob** [comment]
@EugeneKay, the default has not been public domain for a couple of decades now, since the Berne Convention. See [Licensed, License-Free, and Unlicensed Code](http://ar.to/2010/12/licensing-and-unlicensing). Unless @zedshaw should decide to change his license, "all rights reserved", modulo the [GitHub ToS](https://help.github.com/articles/github-terms-of-service) (section F), applies. (The current license file is superfluous, even.)

**Comment by EugeneKay** [comment]
Yes, this is what I'm trying to say. Please fucking read the text instead of just vomiting out a bullshit stock line.

All Rights Reserved grants NO PERMISSIONS AT ALL to you and I for Fuqit. All we are allowed to do is read the source. I am requesting that it be relicensed under a permissive license so that it may legally be used.

**Comment by artob** [comment]
@EugeneKay, thanks for clarifying. I was confused on why you seemed confused, given the author's earlier clear response that this "legal limbo" is exactly his intention for the time being. Anyhow, it's all up to @zedshaw from here on out.

**Comment by astrojuanlu** [comment]
According to http://choosealicense.com/no-license/

> [...] generally speaking, the absence of a license means that default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. ~~This might not be what you intend~~.

So it's clear what we're allowed to do and not to do.

Edit: Added strikethrough.

**Comment by zedshaw** [comment]
It's AGPLv3 now. Keep up people.
