### ISSUE TITLE
hey Zed, testing out this tipper bot, please excuse spamming your issues

### ISSUE THREAD

**Issue by deepthawtz** [zedshaw/fuqit#11]
@GitCash send 0.008 BCH to @zedshaw

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/195/image.png)](https://gitcash.io/claim/zedshaw)
@zedshaw

**Comment by deepthawtz** [comment]
doh, @GitCash send 0.006 BCH to @zedshaw

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/196/image.png)](https://gitcash.io/claim/zedshaw)
@zedshaw
