### ISSUE TITLE
Mailing Address for Convertible Note

### ISSUE THREAD

**Issue by tdavis** [zedshaw/fuqit#5]
This is a _paradigm shift_ that comes along once in a generation--perhaps in a _century_. The old MVC is broken and we know that. Too many models, not enough views. Controllers? What's that even mean? Exactly.

I'm so glad that you're open to investment and I think between your revolutionary framework and my years of investing money in ventures that _speak to me_, we could _synergize_ perfectly!

Just give me your address and I'll have my bank cut a check. Look forward to working with you!

**Comment by zedshaw** [comment]
You seem like a really weak VC. I think I'll wait for someone with real balls and wads of cash.
